apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: {{ .Chart.Name }}
  type: NodePort

  ports:
    - name: http
      protocol: TCP
      port: 8008
      targetPort: http

